---
language: node_js
node_js:
  - "4"

sudo: required 
sudo: trusty

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DESPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - npm config set spin false
  - npm install -g bower
  - bower --version
    
install:
  - npm install
  - bower install

after_success:
  if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ember deploy production; fi

script:
  - npm test
